#!/usr/bin/env cbqn

input ← •FLines "inputs/day2.txt"
•Show input

# We've got cbqn! How to get https://github.com/x86y/beacon eludes me. It
# mentioned `nix` so I've setup a nix environment via devcontainers. It was only
# when I got that working did I notce that it uses flakes, so I've no idea how
# to integrate it.

# So in the end, welp, I've done the editing in BQNPAD again, taking care not to
# exceed the character limit. 